service:
  flush: 1
  log_level: info
  http_server: on
  http_listen: 127.0.0.1
  http_port: 2020

pipeline:
  inputs:
    # Collect vLLM application logs
    - name: tail
      path: /app/logs/app.log
      tag: vllm.logs
      parser: json
      refresh_interval: 5
      skip_long_lines: on
      skip_empty_lines: on

    # Fetch metrics and convert to JSON using a Python one-liner
    - name: exec
      command: |
        curl -s -f http://127.0.0.1:8000/metrics | python3 -c "import sys, json; print(json.dumps({l.split()[0]: l.split()[1] for l in sys.stdin if l.startswith('vllm') and len(l.split())==2}))"
      interval_sec: 30
      tag: vllm.metrics

  outputs:
    # Send logs to Cloud Logging via Basic Auth
    - name: http
      match: vllm.logs
      host: ${OPENSEARCH_HOST}
      port: 443
      uri: /
      format: json
      json_date_key: timestamp
      json_date_format: iso8601
      http_user: ${OPENSEARCH_USER}
      http_passwd: ${OPENSEARCH_PASSWORD}
      tls: on
      tls.verify: off
      compress: gzip

    # Send metrics to Cloud Logging via Basic Auth
    - name: http
      match: vllm.metrics
      host: ${OPENSEARCH_HOST}
      port: 443
      uri: /
      format: json
      json_date_key: timestamp
      json_date_format: iso8601
      http_user: ${OPENSEARCH_USER}
      http_passwd: ${OPENSEARCH_PASSWORD}
      tls: on
      tls.verify: off
      compress: gzip
